package com.flightapp.entities;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonFormat.Shape;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "airlines")
public class AirlinesModel {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String flightNo;
	@DynamoDBAttribute
	private String airline;
	@DynamoDBAttribute
	private Integer businessClassSeats;
	@DynamoDBAttribute
	private Integer nonBusinessClassSeats;
	@DynamoDBAttribute
	private Double ticketCost;
	@DynamoDBAttribute
	private String fromPlace;
	@DynamoDBAttribute
	private String toPlace;
	@DynamoDBAttribute
	//@JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS", shape = Shape.STRING)
	@DynamoDBTyped(DynamoDBAttributeType.S)
	private LocalDateTime startTime;
	@DynamoDBAttribute
	//@JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS", shape = Shape.STRING)
	@DynamoDBTyped(DynamoDBAttributeType.S)
	private LocalDateTime endTime;
	@DynamoDBAttribute
	private String instrumentType;
	@DynamoDBAttribute
	private String mealsType;
	@DynamoDBAttribute
	private String is_blocked;

	

}
